services:
  - type: web
    name: interview
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: VITE_SUPABASE_URL
        scope: build
      - key: VITE_SUPABASE_ANON_KEY
        scope: build
      - key: VITE_GROQ_API_KEY_1
        scope: build
      - key: VITE_GROQ_API_KEY_2
        scope: build
